from django.urls import path

from . import views, views_more

urlpatterns = [
    path("", views.home, name="home"),
    path("nepal/", views.regions, name="regions"),
    path("nepal/<slug:region>/", views.region, name="region"),
    path("nepal/<slug:region>/best-time/<slug:month>/", views.region_month, name="region_month"),
    path("nepal/<slug:region>/tours/<slug:theme>/", views.region_theme, name="region_theme"),
    path("nepal/<slug:region>/things-to-do/<slug:kind>/", views.region_kind, name="region_kind"),
    path("nepal/<slug:region>/<slug:place>/", views.place, name="place"),
    path("nepal/<slug:region>/<slug:place>/<slug:exp>/", views.experience, name="experience"),
    path("packages/", views.packages, name="packages"),
    path("packages/<slug:slug>/", views.package, name="package"),
    path("hotels/", views.stays, name="stays"),
    path("hotels/<slug:slug>/", views.stay, name="stay"),
    path("things-to-do/", views.experiences, name="experiences"),
    path("things-to-do/<slug:kind>/", views.experience_kind, name="experience_kind"),
    path("guides/", views.guides, name="guides"),
    path("guides/<slug:slug>/", views.guide, name="guide"),
    path("festivals/", views.festivals, name="festivals"),
    path("festivals/<slug:slug>/", views.festival, name="festival"),
    path("getting-around/", views.routes, name="routes"),
    path("getting-around/<slug:slug>/", views.route, name="route"),
    path("tour-styles/", views.themes, name="themes"),
    path("from-india/", views.origins, name="origins"),
    path("best-time-to-visit-nepal/", views.seasons, name="seasons"),
    path("tools/", views.tools, name="tools"),
    path("tools/season-finder/", views.tool_season, name="tool_season"),
    path("tools/budget-calculator/", views.tool_budget, name="tool_budget"),
    path("tools/altitude-checker/", views.tool_altitude, name="tool_altitude"),
    path("tools/permit-finder/", views.tool_permits, name="tool_permits"),
    path("plan/", views_more.plan, name="plan"),
    path("plan/thank-you/", views_more.plan_thanks, name="plan_thanks"),
    path("enquire/", views_more.enquire, name="enquire"),
    path("blog/", views_more.journal, name="journal"),
    path("blog/topic/<slug:cat>/", views_more.journal, name="journal_cat"),
    path("blog/<slug:slug>/", views_more.post, name="post"),
    path("policies/", views_more.policies, name="policies"),
    path("policies/<slug:slug>/", views_more.policy, name="policy"),
    path("contact/", views_more.contact, name="contact"),
    path("how-booking-works/", views_more.how_we_work, name="how_we_work"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("subscribe/", views_more.subscribe, name="subscribe"),
    path("search.json", views_more.search_index, name="search_index"),
    path("photo-credits/", views.photo_credits, name="photo_credits"),
    path("sitemap/", views.html_sitemap, name="html_sitemap"),
    path("design-system/", views.design_system, name="design_system"),
    path("robots.txt", views.robots, name="robots"),
    path("llms.txt", views.llms, name="llms"),
    # tour styles (heli-tours, trekking, …) and "nepal-tour-package-from-<city>" pages live at the top level
    path("<slug:slug>/", views.theme_or_origin, name="theme"),
]
